"""piloto: vinculo uvis e os

Revision ID: 6324a2cd00fc
Revises: a262d599b76f
Create Date: 2026-01-08 14:22:40.975769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6324a2cd00fc'
down_revision = 'a262d599b76f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piloto_uvis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('piloto_id', sa.Integer(), nullable=False),
    sa.Column('uvis_usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['piloto_id'], ['pilotos.id'], ),
    sa.ForeignKeyConstraint(['uvis_usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('piloto_id', 'uvis_usuario_id', name='uq_piloto_uvis')
    )
    with op.batch_alter_table('piloto_uvis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_piloto_uvis_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index('ix_piloto_uvis_piloto', ['piloto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_piloto_uvis_piloto_id'), ['piloto_id'], unique=False)
        batch_op.create_index('ix_piloto_uvis_uvis', ['uvis_usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_piloto_uvis_uvis_usuario_id'), ['uvis_usuario_id'], unique=False)

    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.create_index('ix_solicitacao_agenda', ['data_agendamento', 'hora_agendamento'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.drop_index('ix_solicitacao_agenda')

    with op.batch_alter_table('piloto_uvis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_piloto_uvis_uvis_usuario_id'))
        batch_op.drop_index('ix_piloto_uvis_uvis')
        batch_op.drop_index(batch_op.f('ix_piloto_uvis_piloto_id'))
        batch_op.drop_index('ix_piloto_uvis_piloto')
        batch_op.drop_index(batch_op.f('ix_piloto_uvis_criado_em'))

    op.drop_table('piloto_uvis')
    # ### end Alembic commands ###
