"""add index

Revision ID: 7b93d7f7f030
Revises: 8401125b2639
Create Date: 2025-12-30 12:05:13.996438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b93d7f7f030'
down_revision = '8401125b2639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('clientes_documento_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_clientes_documento'), ['documento'], unique=True)
        batch_op.create_index(batch_op.f('ix_clientes_email'), ['email'], unique=False)

    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificacoes_apagada_em'), ['apagada_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacoes_criada_em'), ['criada_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacoes_lida_em'), ['lida_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacoes_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.create_index('ix_solicitacao_data_status', ['data_criacao', 'status'], unique=False)
        batch_op.create_index('ix_solicitacao_usuario_data', ['usuario_id', 'data_criacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitacoes_altura_voo'), ['altura_voo'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitacoes_bairro'), ['bairro'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitacoes_cidade'), ['cidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitacoes_data_agendamento'), ['data_agendamento'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitacoes_foco'), ['foco'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitacoes_protocolo'), ['protocolo'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitacoes_tipo_visita'), ['tipo_visita'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitacoes_uf'), ['uf'], unique=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('usuarios_login_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_usuarios_login'), ['login'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_nome_uvis'), ['nome_uvis'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_regiao'), ['regiao'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_tipo_usuario'), ['tipo_usuario'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_tipo_usuario'))
        batch_op.drop_index(batch_op.f('ix_usuarios_regiao'))
        batch_op.drop_index(batch_op.f('ix_usuarios_nome_uvis'))
        batch_op.drop_index(batch_op.f('ix_usuarios_login'))
        batch_op.create_unique_constraint(batch_op.f('usuarios_login_key'), ['login'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitacoes_uf'))
        batch_op.drop_index(batch_op.f('ix_solicitacoes_tipo_visita'))
        batch_op.drop_index(batch_op.f('ix_solicitacoes_protocolo'))
        batch_op.drop_index(batch_op.f('ix_solicitacoes_foco'))
        batch_op.drop_index(batch_op.f('ix_solicitacoes_data_agendamento'))
        batch_op.drop_index(batch_op.f('ix_solicitacoes_cidade'))
        batch_op.drop_index(batch_op.f('ix_solicitacoes_bairro'))
        batch_op.drop_index(batch_op.f('ix_solicitacoes_altura_voo'))
        batch_op.drop_index('ix_solicitacao_usuario_data')
        batch_op.drop_index('ix_solicitacao_data_status')

    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificacoes_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_notificacoes_lida_em'))
        batch_op.drop_index(batch_op.f('ix_notificacoes_criada_em'))
        batch_op.drop_index(batch_op.f('ix_notificacoes_apagada_em'))

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_email'))
        batch_op.drop_index(batch_op.f('ix_clientes_documento'))
        batch_op.create_unique_constraint(batch_op.f('clientes_documento_key'), ['documento'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
