"""adicionando index para filtros

Revision ID: 8401125b2639
Revises: cfe2d073d2b9
Create Date: 2025-12-30 10:27:46.671057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8401125b2639'
down_revision = 'cfe2d073d2b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_nome_cliente'), ['nome_cliente'], unique=False)

    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitacoes_data_criacao'), ['data_criacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitacoes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitacoes_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitacoes_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_solicitacoes_status'))
        batch_op.drop_index(batch_op.f('ix_solicitacoes_data_criacao'))

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_nome_cliente'))
        batch_op.drop_index(batch_op.f('ix_clientes_id'))

    # ### end Alembic commands ###
