"""adiciona piloto_id em usuario e solicitacao

Revision ID: a262d599b76f
Revises: 7b93d7f7f030
Create Date: 2026-01-08 14:10:40.505479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a262d599b76f'
down_revision = '7b93d7f7f030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('piloto_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_solicitacao_piloto_data', ['piloto_id', 'data_criacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitacoes_piloto_id'), ['piloto_id'], unique=False)
        batch_op.create_foreign_key(None, 'pilotos', ['piloto_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('piloto_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_usuarios_piloto_id'), ['piloto_id'], unique=False)
        batch_op.create_foreign_key(None, 'pilotos', ['piloto_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_usuarios_piloto_id'))
        batch_op.drop_column('piloto_id')

    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_solicitacoes_piloto_id'))
        batch_op.drop_index('ix_solicitacao_piloto_data')
        batch_op.drop_column('piloto_id')

    # ### end Alembic commands ###
